export const concepts = [
  {
    id: "kakeya",
    index: "01",
    title: "三维 Kakeya 集",
    subtitle: "在极小空间中容纳所有方向",
    domain: "几何测度论",
    image: "/assets/kakeya-study.png",
  },
  {
    id: "riemann",
    index: "02",
    title: "黎曼猜想",
    subtitle: "素数星空与临界线",
    domain: "解析数论",
    image: "/assets/riemann.png",
  },
  {
    id: "godel",
    index: "03",
    title: "哥德尔不完备定理",
    subtitle: "无法完成的逻辑手稿",
    domain: "数理逻辑",
    image: "/assets/godel.png",
  },
  {
    id: "mandelbrot",
    index: "04",
    title: "曼德博集合",
    subtitle: "无限递归的暮蓝海岸",
    domain: "复动力系统",
    image: "/assets/mandelbrot.png",
  },
  {
    id: "poincare",
    index: "05",
    title: "庞加莱猜想",
    subtitle: "流动收缩的三维宇宙",
    domain: "几何拓扑",
    image: "/assets/poincare.png",
  },
  {
    id: "pnp",
    index: "06",
    title: "P 与 NP",
    subtitle: "可验证却难以找到出口",
    domain: "计算复杂性",
    image: "/assets/p-vs-np.png",
  },
  {
    id: "banach",
    index: "07",
    title: "巴拿赫–塔斯基悖论",
    subtitle: "一个球变成两个球",
    domain: "集合论 · 几何群论",
    image: "/assets/banach-tarski.png",
  },
  {
    id: "fourier",
    index: "08",
    title: "傅里叶变换",
    subtitle: "夜色波浪被分解为频率光束",
    domain: "调和分析",
    image: "/assets/fourier-transform.png",
  },
  {
    id: "cantor",
    index: "09",
    title: "康托尔无穷",
    subtitle: "不断被挖空的蓝色地平线",
    domain: "集合论 · 分形几何",
    image: "/assets/cantor-infinity.png",
  },
  {
    id: "mobius",
    index: "10",
    title: "莫比乌斯环与克莱因瓶",
    subtitle: "没有内外边界的空间",
    domain: "拓扑学",
    image: "/assets/mobius-klein.png",
  },
  {
    id: "navier",
    index: "11",
    title: "纳维–斯托克斯方程",
    subtitle: "深海湍流与未知奇点",
    domain: "偏微分方程 · 流体力学",
    image: "/assets/navier-stokes.png",
  },
];

export const theories = {
  kakeya: {
    ...concepts[0],
    year: "2025 / R³",
    stageLabel: "R³ / INTERACTIVE FIELD",
    stageHint: "拖动旋转 · 滚轮缩放",
    stageAria: "三维 Kakeya 互动模型",
    observation: "OBSERVATION",
    control: {
      label: "线管尺度 δ",
      min: 0.012,
      max: 0.07,
      step: 0.002,
      initial: 0.034,
      digits: 3,
    },
    steps: [
      {
        number: "01",
        label: "看见问题",
        kicker: "一支无限细的针",
        title: "每个方向，都要有一条单位线段",
        body: "设 K 是三维空间中的一个集合。无论给出哪个方向 ω，都能在 K 中找到一条沿该方向放置的单位线段。线段可以移动、交叠，也可以聚集在异常复杂的区域里。",
        math: String.raw`\forall\,\omega\in S^2,\quad \exists\,\ell_\omega\subset K,\ |\ell_\omega|=1`,
        note: "拖动画面观察：这些线段并非整齐穿过同一个中心。",
      },
      {
        number: "02",
        label: "方向球面",
        kicker: "从平面走向空间",
        title: "方向不再是一圈，而是整个球面",
        body: "在三维中，一个方向由球面 S² 上的点表示。Kakeya 集必须同时容纳球面上连续无穷多个方向，因此真正的难点来自方向之间复杂的空间相交。",
        math: String.raw`\omega\in S^2`,
        note: "打开方向层，可以把每一根线理解为球面上一处方向的空间回声。",
      },
      {
        number: "03",
        label: "缩小尺度",
        kicker: "用 δ-线管观察细线",
        title: "越靠近零，结构越像一团重叠的针雾",
        body: "证明中常把无限细线段稍微加粗成半径为 δ 的线管，再研究 δ 不断趋近于零时，它们的并集怎样占据空间。滑动 δ，查看同一方向系统在不同尺度下的形态。",
        math: String.raw`T_\delta(\ell)=\{x:\operatorname{dist}(x,\ell)\leq\delta\}`,
        note: "δ-线管只是尺度邻域，不是有实体厚度的管道。",
      },
      {
        number: "04",
        label: "抵达结论",
        kicker: "王虹 × Joshua Zahl · 2025",
        title: "它可以零体积，却不能少一个维度",
        body: "王虹与 Joshua Zahl 证明：三维 Kakeya 集的 Hausdorff 维数与 Minkowski 维数都必须等于 3。这里的“满维”不等于“必有正体积”。",
        math: String.raw`\dim_{\mathrm H}K=\dim_{\mathrm M}K=3`,
        note: "这是概念性视觉解释，不是完整证明图。",
      },
    ],
  },
  riemann: {
    ...concepts[1],
    year: "1859 / ζ(s)",
    stageLabel: "CRITICAL STRIP / ZERO FIELD",
    stageHint: "拖动旋转 · 改变虚部高度",
    stageAria: "黎曼猜想临界线与零点互动模型",
    observation: "FIELD NOTE",
    control: {
      label: "虚部高度 t",
      min: 0,
      max: 50,
      step: 0.1,
      initial: 14.1,
      digits: 1,
    },
    steps: [
      {
        number: "01",
        label: "素数暗流",
        kicker: "看似散乱的整数星群",
        title: "素数没有周期，却留下统计节奏",
        body: "黎曼把逐个数素数的问题，转化为研究一个复变量函数。欧拉乘积把 ζ 函数与所有素数相连：函数的解析性质会反过来约束素数的整体分布。",
        math: String.raw`\zeta(s)=\sum_{n=1}^{\infty}n^{-s}=\prod_p(1-p^{-s})^{-1}`,
        note: "星点不是素数的空间坐标，而是“每个素数都参与同一函数”的视觉隐喻。",
      },
      {
        number: "02",
        label: "进入复平面",
        kicker: "实部 σ × 虚部 t",
        title: "真正的谜题藏在一条带状区域",
        body: "除负偶数处的平凡零点外，非平凡零点都位于 0 < Re(s) < 1 的临界带。函数方程使零点关于 Re(s)=1/2 对称。",
        math: String.raw`0<\operatorname{Re}(s)<1`,
        note: "两侧边界是已知的；猜想关心的是带内所有非平凡零点是否完全落在中线。",
      },
      {
        number: "03",
        label: "临界线",
        kicker: "σ = 1/2",
        title: "每个非平凡零点，都应落在同一条线上",
        body: "黎曼猜想断言：所有非平凡零点的实部都等于 1/2。滑动 t，沿临界线向上巡游；14.1347… 附近出现第一个非平凡零点。",
        math: String.raw`\zeta\!\left(\frac12+it\right)=0`,
        note: "亮起的节点代表已知零点位置的示意采样，不等同于完整数值计算器。",
      },
      {
        number: "04",
        label: "为何重要",
        kicker: "误差项被临界线控制",
        title: "零点的位置，决定素数计数有多平稳",
        body: "素数定理给出 π(x) 的主趋势，而黎曼猜想会显著收紧误差界。它不是生成下一个素数的快捷方式，而是对素数总体分布规律的深层约束。",
        math: String.raw`\pi(x)=\operatorname{Li}(x)+O\!\left(\sqrt{x}\log x\right)`,
        note: "成立时，素数的“波动噪声”被限制在近似平方根尺度。",
      },
      {
        number: "05",
        label: "尚未证明",
        kicker: "大量验证 ≠ 普遍证明",
        title: "再多已检查零点，也无法替代对无限的证明",
        body: "计算已经验证极高范围内的零点位于临界线，但猜想要求对无穷多个零点都成立。它仍是克雷数学研究所的千禧年难题之一。",
        math: String.raw`\forall\rho,\ \zeta(\rho)=0,\ 0<\Re(\rho)<1\Rightarrow\Re(\rho)=\frac12`,
        note: "可视化展示结构与证据，不把尚未解决的问题写成既成定理。",
      },
    ],
  },
  godel: {
    ...concepts[2],
    year: "1931 / META",
    stageLabel: "FORMAL SYSTEM / SELF-REFERENCE",
    stageHint: "拖动旋转 · 增加编码层级",
    stageAria: "哥德尔不完备定理自指结构互动模型",
    observation: "MARGIN NOTE",
    control: {
      label: "自指层级 n",
      min: 1,
      max: 7,
      step: 1,
      initial: 3,
      digits: 0,
    },
    steps: [
      {
        number: "01",
        label: "形式系统",
        kicker: "公理、符号与推演规则",
        title: "先把证明变成可以机械检查的符号链",
        body: "形式系统从有限或可有效描述的公理出发，按明确规则推出定理。哥德尔讨论的是足够表达基本算术、并且能有效枚举公理的系统。",
        math: String.raw`T\vdash\varphi`,
        note: "“形式化”要求每一步都能被规则检查，不依赖直觉跳跃。",
      },
      {
        number: "02",
        label: "算术编码",
        kicker: "让句子谈论句子",
        title: "符号、公式与证明都可以被编码成整数",
        body: "哥德尔编号把语法对象映射为自然数，于是“x 是某个公式的证明”也能在算术内部表达。系统获得了一面能够描述自身语法的镜子。",
        math: String.raw`\ulcorner\varphi\urcorner\in\mathbb N`,
        note: "增加层级，观察一条陈述如何被编码、再作为另一条陈述的对象。",
      },
      {
        number: "03",
        label: "自指句",
        kicker: "这句话在 T 中不可证明",
        title: "对角化制造出关于自身可证性的陈述",
        body: "借助对角引理，可以构造句子 G，使它在系统内等价于“G 不可在 T 中证明”。这不是普通语言悖论，而是严格的算术构造。",
        math: String.raw`T\vdash G\leftrightarrow\neg\operatorname{Prov}_T(\ulcorner G\urcorner)`,
        note: "画面中的缺口表示系统无法从内部把这条回路完全封闭。",
      },
      {
        number: "04",
        label: "第一定理",
        kicker: "一致性带来不完备",
        title: "足够强且一致的系统，总有无法决定的句子",
        body: "在标准条件下，如果 T 一致，就存在句子既不能在 T 中证明，也不能在 T 中否证。这里的“不完备”是特定形式系统的边界，不是说所有数学都不可靠。",
        math: String.raw`T\nvdash G\quad\text{且}\quad T\nvdash\neg G`,
        note: "更换或加强公理可以决定某些旧问题，但新的系统仍会出现自己的不可判定句。",
      },
      {
        number: "05",
        label: "第二定理",
        kicker: "系统无法独自担保自身",
        title: "系统不能在内部证明自己的相容性",
        body: "满足条件且一致的系统 T，不能在自身内部证明 Con(T)。证明相容性通常需要站到更强的元系统中，而那个元系统也会面对同类问题。",
        math: String.raw`T\nvdash\operatorname{Con}(T)`,
        note: "不完备性划出形式证明的结构边界，并不否定数学证明本身。",
      },
    ],
  },
  mandelbrot: {
    ...concepts[3],
    year: "1980 / z² + c",
    stageLabel: "COMPLEX DYNAMICS / ESCAPE FIELD",
    stageHint: "拖动旋转 · 增加迭代深度",
    stageAria: "曼德博集合逃逸时间互动模型",
    observation: "COAST NOTE",
    control: {
      label: "迭代深度 N",
      min: 8,
      max: 96,
      step: 4,
      initial: 48,
      digits: 0,
    },
    steps: [
      {
        number: "01",
        label: "一条规则",
        kicker: "从 z₀ = 0 出发",
        title: "把结果平方，再加上同一个复数 c",
        body: "对复平面中的每个参数 c，从 z₀=0 开始重复迭代。规则极短，但不同 c 会产生完全不同的长期行为。",
        math: String.raw`z_{n+1}=z_n^2+c,\qquad z_0=0`,
        note: "拖动画面时，你看到的是参数平面，不是单条轨道在物理空间中的路径。",
      },
      {
        number: "02",
        label: "是否逃逸",
        kicker: "有界与发散的分界",
        title: "轨道永远有界的 c，组成曼德博集合",
        body: "如果迭代序列始终没有逃向无穷远，则参数 c 属于集合 M。只要某一步满足 |zₙ|>2，之后就必然逃逸。",
        math: String.raw`M=\{c\in\mathbb C:\{z_n\}_{n\ge0}\ \text{有界}\}`,
        note: "深色内陆表示未逃逸区域；海岸亮度表示逃逸速度的层次。",
      },
      {
        number: "03",
        label: "增加迭代",
        kicker: "海岸线逐步显影",
        title: "有限计算只能得到越来越精细的近似",
        body: "把最大迭代次数 N 调高，更多靠近边界的点才显露真实归属。边界附近存在极长的暂态，因此也是细节最密集的区域。",
        math: String.raw`n_{\mathrm{escape}}(c)=\min\{n:|z_n|>2\}`,
        note: "N 越大，轮廓越稳定，但任何有限像素图仍只是连续集合的采样。",
      },
      {
        number: "04",
        label: "无限细节",
        kicker: "自相似，但并非处处复制",
        title: "放大后会遇见相似结构，也会遇见全新的海湾",
        body: "曼德博集合的边界具有分形结构。小型“曼德博宝宝”会反复出现，但其周围纹理受不同周期成分影响，并不是简单复制粘贴。",
        math: String.raw`\partial M\ \text{具有无限层级的局部结构}`,
        note: "“自相似”在这里包含变形与新结构，不等于每一级都完全相同。",
      },
      {
        number: "05",
        label: "参数地图",
        kicker: "一张动力系统的总索引",
        title: "每个点都对应一种二次迭代系统",
        body: "M 不是单一分形图案，而是所有二次多项式 z²+c 的参数地图。主心形、圆瓣和细丝记录了吸引周期与稳定区域的组织方式。",
        math: String.raw`f_c(z)=z^2+c`,
        note: "从一条递推式出发，参数空间长出了完整的动力学地理。",
      },
    ],
  },
  poincare: {
    ...concepts[4],
    year: "1904—2003 / S³",
    stageLabel: "3-MANIFOLD / RICCI FLOW",
    stageHint: "拖动旋转 · 推进流动时间",
    stageAria: "庞加莱猜想与曲率流互动模型",
    observation: "TOPOLOGY NOTE",
    control: {
      label: "流动时间 τ",
      min: 0,
      max: 1,
      step: 0.02,
      initial: 0.12,
      digits: 2,
    },
    steps: [
      {
        number: "01",
        label: "辨认空间",
        kicker: "局部像三维欧氏空间",
        title: "三维流形可以弯曲，却没有局部断裂",
        body: "三维流形在每个足够小的邻域里都像普通三维空间，但整体可能拥有复杂拓扑。问题是：哪些全局条件足以认出三维球面 S³？",
        math: String.raw`M^3\ \text{locally resembles}\ \mathbb R^3`,
        note: "画面表现的是抽象流形的结构，不是嵌入四维空间后的真实外观。",
      },
      {
        number: "02",
        label: "收缩闭环",
        kicker: "单连通",
        title: "每一条闭合环路，都能连续缩成一个点",
        body: "若流形中任何闭合曲线都可以在空间内部连续收缩为一点，它就是单连通的。甜甜圈不满足，因为绕洞的环无法越过洞口。",
        math: String.raw`\pi_1(M)=0`,
        note: "闭环能否收缩，是探测空间中“洞”的核心方法。",
      },
      {
        number: "03",
        label: "猜想",
        kicker: "紧致 × 无边界 × 单连通",
        title: "满足这些条件的三维空间，应当就是三维球面",
        body: "庞加莱猜想断言：每个闭的、单连通三维流形都与三维球面同胚。这里说的是拓扑等价，不要求几何形状或曲率一模一样。",
        math: String.raw`M^3\ \text{closed},\ \pi_1(M)=0\Rightarrow M\cong S^3`,
        note: "可以拉伸和弯曲，但不能撕裂、粘合或穿洞。",
      },
      {
        number: "04",
        label: "曲率流",
        kicker: "让几何像热量一样扩散",
        title: "Ricci 流逐渐抚平曲率，也会暴露奇点",
        body: "Hamilton 提出用 Ricci 流演化度量。高曲率区域会被重新分配，但流动可能形成奇点；理解并处理这些奇点是证明的核心障碍。",
        math: String.raw`\frac{\partial g}{\partial t}=-2\,\operatorname{Ric}(g)`,
        note: "推进 τ，表面逐渐均匀；这只是曲率扩散的概念模型。",
      },
      {
        number: "05",
        label: "佩雷尔曼",
        kicker: "熵、无局部塌缩与手术",
        title: "控制奇点之后，空间的拓扑类型被完整识别",
        body: "佩雷尔曼在 2002—2003 年的预印本中完成关键论证，建立 Ricci 流带手术所需的控制，并证明更广泛的 Thurston 几何化猜想，庞加莱猜想随之成立。",
        math: String.raw`M^3\simeq S^3`,
        note: "这章呈现证明路线的骨架，不把几何分析的技术细节压缩成一次视觉变形。",
      },
    ],
  },
  pnp: {
    ...concepts[5],
    year: "1971 / COMPLEXITY",
    stageLabel: "SEARCH SPACE / CERTIFICATE PATH",
    stageHint: "拖动旋转 · 增加问题规模",
    stageAria: "P 与 NP 搜索空间互动模型",
    observation: "COMPLEXITY NOTE",
    control: {
      label: "问题规模 n",
      min: 4,
      max: 12,
      step: 1,
      initial: 7,
      digits: 0,
    },
    steps: [
      {
        number: "01",
        label: "快速求解",
        kicker: "P：多项式时间",
        title: "有些问题能随输入规模可控地增长",
        body: "P 类包含可以由确定性算法在多项式时间内求解的判定问题。多项式不是“永远很快”，但它把增长控制在理论上可扩展的范围内。",
        math: String.raw`\mathrm P=\bigcup_{k\ge1}\operatorname{TIME}(n^k)`,
        note: "改变规模 n，观察搜索空间增长；模型展示趋势，不代表某个具体算法的实际耗时。",
      },
      {
        number: "02",
        label: "快速验证",
        kicker: "NP：给出证书就能检查",
        title: "出口也许难找，但一条正确路径可以很快验明",
        body: "NP 类问题的“是”实例拥有多项式长度证书，并可在多项式时间内验证。NP 不是“非多项式”，也不等于所有困难问题。",
        math: String.raw`x\in L\iff\exists y,\ |y|\le\operatorname{poly}(|x|),\ V(x,y)=1`,
        note: "玫红路径代表一份候选证书；检查路径比从全部岔路中发现它更直接。",
      },
      {
        number: "03",
        label: "核心问题",
        kicker: "P 是否等于 NP？",
        title: "凡是容易验证的答案，也都容易找到吗",
        body: "我们知道 P⊆NP，但不知道包含是否严格。如果 P=NP，大量搜索、规划与组合优化问题会获得全新的理论算法；若不等，则存在本质上的求解—验证鸿沟。",
        math: String.raw`\mathrm P\stackrel{?}{=}\mathrm{NP}`,
        note: "问题讨论最坏情况与渐近复杂度，不是说每个现实实例都同样难。",
      },
      {
        number: "04",
        label: "完全问题",
        kicker: "所有 NP 问题汇聚的关口",
        title: "解出任意一个 NP 完全问题，就会解出整个 NP",
        body: "SAT 是第一个被证明 NP 完全的问题。任何 NP 问题都能在多项式时间归约到 SAT；因此若 SAT∈P，则 P=NP。",
        math: String.raw`\mathrm{SAT}\in\mathrm P\Rightarrow\mathrm P=\mathrm{NP}`,
        note: "图中的多条支路汇向同一关口，表示归约关系而非问题表面的相似。",
      },
      {
        number: "05",
        label: "仍是开放问题",
        kicker: "证据很多，证明仍缺席",
        title: "几十年的失败，尚未构成 P≠NP 的证明",
        body: "复杂性理论已经发现多种证明障碍，也建立大量条件性结果，但 P 与 NP 的关系依然未知。它同样是千禧年难题之一。",
        math: String.raw`\mathrm P\subseteq\mathrm{NP}\quad\text{已知；等号未知}`,
        note: "系统明确保留“未知”状态，避免把广泛信念误写成定理。",
      },
    ],
  },
  banach: {
    ...concepts[6],
    year: "1924 / AC",
    stageLabel: "EQUIDECOMPOSITION / NON-MEASURABLE PIECES",
    stageHint: "拖动旋转 · 推进重组过程",
    stageAria: "巴拿赫–塔斯基悖论分解与重组互动模型",
    observation: "SET THEORY NOTE",
    control: {
      label: "重组进度 τ",
      min: 0,
      max: 1,
      step: 0.02,
      initial: 0,
      digits: 2,
    },
    steps: [
      {
        number: "01",
        label: "一个实心球",
        kicker: "普通体积的直觉",
        title: "把一个球分成有限块，怎么可能得到两个同样大的球",
        body: "在日常几何里，有限分割后的总体积应保持不变。巴拿赫–塔斯基定理却说：三维实心球可以分成有限个集合，只用旋转和平移，重新拼成两个与原球全等的球。",
        math: String.raw`B\sim B\sqcup B`,
        note: "画面中的点云只是集合分组的视觉语言，不代表把真实物质切成碎片。",
      },
      {
        number: "02",
        label: "非可测块",
        kicker: "它们不是普通几何小块",
        title: "悖论藏在无法定义体积的集合里",
        body: "分解得到的集合极度离散，不能赋予与通常体积兼容的勒贝格测度。它们不是有光滑边界的小块，也无法通过有限精度加工出来。",
        math: String.raw`\mu(A_i)\ \text{不存在}`,
        note: "因此不能把“每一块体积相加”用于这些特殊集合。",
      },
      {
        number: "03",
        label: "选择公理",
        kicker: "从无穷轨道中各取代表",
        title: "选择公理让我们从不可数多个轨道中同时选点",
        body: "经典证明利用自由群作用，把球面上的点按旋转轨道分类，再借助选择公理选取代表元。所得集合通常无法显式写出或逐点构造。",
        math: String.raw`\mathrm{AC}\Rightarrow\text{存在轨道代表集}`,
        note: "滑动 τ，五种颜色代表有限组非可测集合被重新定位。",
      },
      {
        number: "04",
        label: "等分解",
        kicker: "旋转 × 平移",
        title: "群的非交换结构制造出两份完整轨道",
        body: "三维旋转群中包含自由子群，其轨道可以发生看似复制的等分解。经过有限次刚体变换，这些集合分别覆盖两个球。",
        math: String.raw`B=\bigsqcup_{i=1}^{m}A_i,\qquad B\sqcup B=\bigsqcup_{i=1}^{m}g_iA_i`,
        note: "定理没有复制点；它改变的是点集被归入哪一个目标球。",
      },
      {
        number: "05",
        label: "为何不矛盾",
        kicker: "体积可加性没有适用",
        title: "数学定理成立，但不会制造现实中的物质",
        body: "普通体积只对可测集合满足可数可加性。巴拿赫–塔斯基的分块不可测，因此“一个体积等于两个体积”的推理前提已经失效。",
        math: String.raw`\text{不可测}\ \not\Rightarrow\ \mu(B)=2\mu(B)`,
        note: "它揭示选择公理、测度与对称群之间的边界，而不是物理复制术。",
      },
    ],
  },
  fourier: {
    ...concepts[7],
    year: "1822 / FREQUENCY",
    stageLabel: "SIGNAL / FREQUENCY SPECTRUM",
    stageHint: "拖动旋转 · 增加谐波数量",
    stageAria: "傅里叶变换波形分解互动模型",
    observation: "SPECTRUM NOTE",
    control: {
      label: "谐波数量 k",
      min: 1,
      max: 9,
      step: 1,
      initial: 4,
      digits: 0,
    },
    steps: [
      {
        number: "01",
        label: "复杂波形",
        kicker: "时间域中的海浪",
        title: "一条看似混乱的波，可能由许多简单振动叠加",
        body: "声音、光、海浪和传感器信号都可以随时间变化。傅里叶思想把复杂信号看成不同频率、振幅与相位的正弦波叠加。",
        math: String.raw`f(t)=\sum_k A_k\cos(2\pi\xi_k t+\phi_k)`,
        note: "左侧复合波来自当前可见谐波的叠加；增加 k 会带来更细的形状。",
      },
      {
        number: "02",
        label: "基底振动",
        kicker: "每个频率是一种坐标方向",
        title: "正弦与余弦构成描述信号的频率语言",
        body: "在线性空间中，频率成分像一组基向量。投影到某个频率，就能测出该振动在原信号中占多少。",
        math: String.raw`\langle f,e^{2\pi i\xi t}\rangle`,
        note: "中部各行展示不同频率的纯振动，右侧光束对应其强度。",
      },
      {
        number: "03",
        label: "变换",
        kicker: "从时间域走向频率域",
        title: "积分把每个频率的振幅与相位抽取出来",
        body: "连续傅里叶变换把函数 f(t) 映射为频谱 F(ξ)。复数值同时记录振幅与相位，逆变换则把所有频率重新合成为原信号。",
        math: String.raw`\widehat f(\xi)=\int_{-\infty}^{\infty}f(t)e^{-2\pi i\xi t}\,dt`,
        note: "频谱不是另一段声音，而是描述声音由哪些频率组成的坐标表。",
      },
      {
        number: "04",
        label: "分辨率",
        kicker: "时间与频率不能同时无限精确",
        title: "观察窗口越短，频率分辨率通常越模糊",
        body: "信号在时间上的集中程度与频谱宽度存在不确定性关系。短促脉冲需要许多频率共同合成，而纯单频波会延伸很长时间。",
        math: String.raw`\Delta t\,\Delta\xi\ge\frac{1}{4\pi}`,
        note: "这是一种结构性权衡，不是测量设备不够好造成的偶然误差。",
      },
      {
        number: "05",
        label: "进入应用",
        kicker: "压缩、成像、通信与方程",
        title: "换到频率域后，许多复杂运算会变得简单",
        body: "卷积会变成频谱相乘，微分会变成乘以频率。音频压缩、MRI、图像处理、无线通信和偏微分方程都大量使用这套语言。",
        math: String.raw`\widehat{f*g}=\widehat f\,\widehat g`,
        note: "傅里叶变换的力量来自同一个对象在两种坐标系统中的互补可见性。",
      },
    ],
  },
  cantor: {
    ...concepts[8],
    year: "1874—1883 / ∞",
    stageLabel: "CANTOR SET / INFINITE CARDINALITY",
    stageHint: "拖动旋转 · 增加挖空层级",
    stageAria: "康托尔集与无穷层级互动模型",
    observation: "INFINITY NOTE",
    control: {
      label: "挖空层级 n",
      min: 0,
      max: 7,
      step: 1,
      initial: 4,
      digits: 0,
    },
    steps: [
      {
        number: "01",
        label: "不断挖空",
        kicker: "每次删去中间三分之一",
        title: "区间被反复挖空，却永远留下新的碎片",
        body: "从 [0,1] 开始，删除中间三分之一，再对剩下的每个闭区间重复。有限阶段仍是许多线段；无限继续后得到康托尔集。",
        math: String.raw`C=\bigcap_{n=0}^{\infty}C_n`,
        note: "滑动 n 查看有限近似；真正的康托尔集对应永不停止的极限。",
      },
      {
        number: "02",
        label: "长度归零",
        kicker: "剩余总长度趋近于零",
        title: "留下的点不可数，集合的总长度却是零",
        body: "第 n 阶段留下总长度 (2/3)ⁿ，极限为 0。但康托尔集不为空，而且包含不可数多个点。",
        math: String.raw`|C_n|=\left(\frac23\right)^n\longrightarrow0`,
        note: "“长度为零”不等于“没有点”，测度与基数描述的是不同性质。",
      },
      {
        number: "03",
        label: "三进制编码",
        kicker: "只使用数字 0 与 2",
        title: "每个留下的点都对应一条无限选择序列",
        body: "康托尔集中的点可写成只含 0 和 2 的三进制展开。把 0、2 替换成二进制的 0、1，就能与无限二进制序列建立联系。",
        math: String.raw`x=0.a_1a_2\cdots{}_3,\qquad a_i\in\{0,2\}`,
        note: "每次选择左段或右段，都会写下序列中的下一位。",
      },
      {
        number: "04",
        label: "无穷有大小",
        kicker: "可数与不可数",
        title: "自然数无穷与实数无穷并不是同一种大小",
        body: "自然数集合是可数无穷；实数区间不可数。康托尔的对角论证说明：任何声称列出全部实数的清单，都能构造出一个未被列出的新数。",
        math: String.raw`|\mathbb N|=\aleph_0<|\mathbb R|`,
        note: "无穷基数比较使用一一对应，而不是有限集合的逐个计数。",
      },
      {
        number: "05",
        label: "分形维数",
        kicker: "介于点与线之间",
        title: "它的维数不是整数，而是 log 2 / log 3",
        body: "康托尔集由两个缩小到三分之一的自身副本组成。相似维数满足 2·3⁻ᵈ=1，因此落在 0 与 1 之间。",
        math: String.raw`\dim_{\mathrm H}C=\frac{\log2}{\log3}`,
        note: "分形维数衡量缩放时细节增长速度，不是把空间真的切出半个坐标轴。",
      },
    ],
  },
  mobius: {
    ...concepts[9],
    year: "1858 / NON-ORIENTABLE",
    stageLabel: "ONE-SIDED SURFACES / IMMERSION",
    stageHint: "拖动旋转 · 穿行曲面",
    stageAria: "莫比乌斯环与克莱因瓶互动模型",
    observation: "TOPOLOGY NOTE",
    control: {
      label: "曲面旅程 u",
      min: 0,
      max: 1,
      step: 0.02,
      initial: 0.18,
      digits: 2,
    },
    steps: [
      {
        number: "01",
        label: "半扭转粘合",
        kicker: "纸带首尾反向相接",
        title: "一次半扭转，把两面变成同一个面",
        body: "将长方形纸带的一端旋转 180° 后与另一端粘合，就得到莫比乌斯带。沿表面一直走，会在不跨越边界的情况下回到原处的“另一面”。",
        math: String.raw`(0,t)\sim(1,1-t)`,
        note: "暖色轨迹沿单一表面运行一周后翻转局部朝向。",
      },
      {
        number: "02",
        label: "不可定向",
        kicker: "无法全局一致地选择正面",
        title: "局部法向量绕一圈后会反向",
        body: "在可定向曲面上，可以连续选择一致的法向方向；莫比乌斯带做不到。一个小箭头沿带移动一周，会变成原来的反方向。",
        math: String.raw`w_1(M)\ne0`,
        note: "不可定向不是表面破损，而是全局粘合方式造成的拓扑性质。",
      },
      {
        number: "03",
        label: "一条边界",
        kicker: "边缘也是同一条闭合曲线",
        title: "莫比乌斯带只有一个面，也只有一条边界",
        body: "沿任一边缘持续行走，会遍历看似左右两侧的全部边缘后回到起点。它与普通圆环带的两条边界不同。",
        math: String.raw`|\pi_0(\partial M)|=1`,
        note: "画面左侧是带边界的曲面；边界线被强调为一条连续闭环。",
      },
      {
        number: "04",
        label: "克莱因瓶",
        kicker: "无边界的不可定向曲面",
        title: "再粘合一对边界，就得到没有边界的克莱因瓶",
        body: "克莱因瓶可由方形的两对边按特定方向粘合得到。它是闭的不可定向曲面，没有内外之分，也没有边界。",
        math: String.raw`\partial K=\varnothing`,
        note: "右侧模型在三维中必须自相交；交叉处不是曲面真正相交。",
      },
      {
        number: "05",
        label: "需要四维",
        kicker: "三维只能看到浸入",
        title: "真正无自交的克莱因瓶需要四维空间",
        body: "克莱因瓶不能无自交地嵌入三维欧氏空间，但可以在四维中嵌入。常见玻璃模型只是三维浸入的投影。",
        math: String.raw`K\looparrowright\mathbb R^3,\qquad K\hookrightarrow\mathbb R^4`,
        note: "旋转模型有助于理解投影，却不能把第四维完整显示出来。",
      },
    ],
  },
  navier: {
    ...concepts[10],
    year: "1822— / 3D FLOW",
    stageLabel: "INCOMPRESSIBLE FLOW / VORTICITY FIELD",
    stageHint: "拖动旋转 · 增加雷诺数",
    stageAria: "纳维–斯托克斯湍流与涡量互动模型",
    observation: "FLUID NOTE",
    control: {
      label: "雷诺数 Re",
      min: 20,
      max: 1200,
      step: 20,
      initial: 220,
      digits: 0,
    },
    steps: [
      {
        number: "01",
        label: "流体速度场",
        kicker: "每一点都有速度与压力",
        title: "方程描述流体如何随时间推动、旋转与扩散",
        body: "不可压缩纳维–斯托克斯方程把惯性、压力、黏性和外力放在同一个速度场 u(x,t) 中。散度为零表示流体局部不被压缩。",
        math: String.raw`\partial_tu+(u\cdot\nabla)u=-\nabla p+\nu\Delta u+f,\quad\nabla\cdot u=0`,
        note: "画面中的流线是速度场采样，不是固定不动的物质细丝。",
      },
      {
        number: "02",
        label: "黏性与惯性",
        kicker: "雷诺数控制竞争",
        title: "低雷诺数倾向平滑，高雷诺数更容易产生复杂涡旋",
        body: "雷诺数衡量惯性效应与黏性效应的比值。增大 Re，流线从层流逐渐出现更多尺度的卷曲与不稳定。",
        math: String.raw`\operatorname{Re}=\frac{UL}{\nu}`,
        note: "滑块改变的是概念性湍流强度，不对应某一种具体流体实验。",
      },
      {
        number: "03",
        label: "涡量",
        kicker: "局部旋转的密度",
        title: "速度场的旋度揭示流体在哪里打旋",
        body: "涡量 ω=∇×u 描述局部旋转。在三维中，涡线可以被速度梯度拉伸，这使小尺度结构更难控制。",
        math: String.raw`\omega=\nabla\times u`,
        note: "亮起的旋涡核心代表涡量增强区域，而非必然形成数学奇点。",
      },
      {
        number: "04",
        label: "能量级联",
        kicker: "从大涡走向小涡",
        title: "湍流把能量输送到越来越细的尺度，再由黏性耗散",
        body: "三维湍流常表现为大尺度结构不断分裂成小尺度涡旋。理解这种级联与间歇性，是连接方程、数值模拟和真实流动的核心。",
        math: String.raw`E(k)\sim k^{-5/3}`,
        note: "−5/3 律属于经典惯性区统计图景，不是所有流动状态的逐点定律。",
      },
      {
        number: "05",
        label: "未知奇点",
        kicker: "三维存在性与光滑性",
        title: "光滑初值会永远保持光滑吗，我们仍不知道",
        body: "三维不可压缩方程存在全局弱解，但尚未证明所有光滑有限能量初值都产生全局光滑解，也未构造出有限时间爆破解。这是千禧年难题之一。",
        math: String.raw`\|u(\cdot,t)\|_{H^s}<\infty\ \text{for all }t\ ?`,
        note: "数值中的尖峰可能来自分辨率或模型；真正的数学奇点需要严格证明。",
      },
    ],
  },
};
