export const concepts = [
  {
    id: "kakeya",
    index: "01",
    title: "三维 Kakeya 集",
    subtitle: "在极小空间中容纳所有方向",
    domain: "几何测度论",
    image: "/assets/kakeya-study.png",
  },
  {
    id: "riemann",
    index: "02",
    title: "黎曼猜想",
    subtitle: "素数星空与临界线",
    domain: "解析数论",
    image: "/assets/riemann.png",
  },
  {
    id: "godel",
    index: "03",
    title: "哥德尔不完备定理",
    subtitle: "无法完成的逻辑手稿",
    domain: "数理逻辑",
    image: "/assets/godel.png",
  },
  {
    id: "mandelbrot",
    index: "04",
    title: "曼德博集合",
    subtitle: "无限递归的暮蓝海岸",
    domain: "复动力系统",
    image: "/assets/mandelbrot.png",
  },
  {
    id: "poincare",
    index: "05",
    title: "庞加莱猜想",
    subtitle: "流动收缩的三维宇宙",
    domain: "几何拓扑",
    image: "/assets/poincare.png",
  },
  {
    id: "pnp",
    index: "06",
    title: "P 与 NP",
    subtitle: "可验证却难以找到出口",
    domain: "计算复杂性",
    image: "/assets/p-vs-np.png",
  },
];

export const theories = {
  kakeya: {
    ...concepts[0],
    year: "2025 / R³",
    stageLabel: "R³ / INTERACTIVE FIELD",
    stageHint: "拖动旋转 · 滚轮缩放",
    stageAria: "三维 Kakeya 互动模型",
    observation: "OBSERVATION",
    control: {
      label: "线管尺度 δ",
      min: 0.012,
      max: 0.07,
      step: 0.002,
      initial: 0.034,
      digits: 3,
    },
    steps: [
      {
        number: "01",
        label: "看见问题",
        kicker: "一支无限细的针",
        title: "每个方向，都要有一条单位线段",
        body: "设 K 是三维空间中的一个集合。无论给出哪个方向 ω，都能在 K 中找到一条沿该方向放置的单位线段。线段可以移动、交叠，也可以聚集在异常复杂的区域里。",
        math: String.raw`\forall\,\omega\in S^2,\quad \exists\,\ell_\omega\subset K,\ |\ell_\omega|=1`,
        note: "拖动画面观察：这些线段并非整齐穿过同一个中心。",
      },
      {
        number: "02",
        label: "方向球面",
        kicker: "从平面走向空间",
        title: "方向不再是一圈，而是整个球面",
        body: "在三维中，一个方向由球面 S² 上的点表示。Kakeya 集必须同时容纳球面上连续无穷多个方向，因此真正的难点来自方向之间复杂的空间相交。",
        math: String.raw`\omega\in S^2`,
        note: "打开方向层，可以把每一根线理解为球面上一处方向的空间回声。",
      },
      {
        number: "03",
        label: "缩小尺度",
        kicker: "用 δ-线管观察细线",
        title: "越靠近零，结构越像一团重叠的针雾",
        body: "证明中常把无限细线段稍微加粗成半径为 δ 的线管，再研究 δ 不断趋近于零时，它们的并集怎样占据空间。滑动 δ，查看同一方向系统在不同尺度下的形态。",
        math: String.raw`T_\delta(\ell)=\{x:\operatorname{dist}(x,\ell)\leq\delta\}`,
        note: "δ-线管只是尺度邻域，不是有实体厚度的管道。",
      },
      {
        number: "04",
        label: "抵达结论",
        kicker: "王虹 × Joshua Zahl · 2025",
        title: "它可以零体积，却不能少一个维度",
        body: "王虹与 Joshua Zahl 证明：三维 Kakeya 集的 Hausdorff 维数与 Minkowski 维数都必须等于 3。这里的“满维”不等于“必有正体积”。",
        math: String.raw`\dim_{\mathrm H}K=\dim_{\mathrm M}K=3`,
        note: "这是概念性视觉解释，不是完整证明图。",
      },
    ],
  },
  riemann: {
    ...concepts[1],
    year: "1859 / ζ(s)",
    stageLabel: "CRITICAL STRIP / ZERO FIELD",
    stageHint: "拖动旋转 · 改变虚部高度",
    stageAria: "黎曼猜想临界线与零点互动模型",
    observation: "FIELD NOTE",
    control: {
      label: "虚部高度 t",
      min: 0,
      max: 50,
      step: 0.1,
      initial: 14.1,
      digits: 1,
    },
    steps: [
      {
        number: "01",
        label: "素数暗流",
        kicker: "看似散乱的整数星群",
        title: "素数没有周期，却留下统计节奏",
        body: "黎曼把逐个数素数的问题，转化为研究一个复变量函数。欧拉乘积把 ζ 函数与所有素数相连：函数的解析性质会反过来约束素数的整体分布。",
        math: String.raw`\zeta(s)=\sum_{n=1}^{\infty}n^{-s}=\prod_p(1-p^{-s})^{-1}`,
        note: "星点不是素数的空间坐标，而是“每个素数都参与同一函数”的视觉隐喻。",
      },
      {
        number: "02",
        label: "进入复平面",
        kicker: "实部 σ × 虚部 t",
        title: "真正的谜题藏在一条带状区域",
        body: "除负偶数处的平凡零点外，非平凡零点都位于 0 < Re(s) < 1 的临界带。函数方程使零点关于 Re(s)=1/2 对称。",
        math: String.raw`0<\operatorname{Re}(s)<1`,
        note: "两侧边界是已知的；猜想关心的是带内所有非平凡零点是否完全落在中线。",
      },
      {
        number: "03",
        label: "临界线",
        kicker: "σ = 1/2",
        title: "每个非平凡零点，都应落在同一条线上",
        body: "黎曼猜想断言：所有非平凡零点的实部都等于 1/2。滑动 t，沿临界线向上巡游；14.1347… 附近出现第一个非平凡零点。",
        math: String.raw`\zeta\!\left(\frac12+it\right)=0`,
        note: "亮起的节点代表已知零点位置的示意采样，不等同于完整数值计算器。",
      },
      {
        number: "04",
        label: "为何重要",
        kicker: "误差项被临界线控制",
        title: "零点的位置，决定素数计数有多平稳",
        body: "素数定理给出 π(x) 的主趋势，而黎曼猜想会显著收紧误差界。它不是生成下一个素数的快捷方式，而是对素数总体分布规律的深层约束。",
        math: String.raw`\pi(x)=\operatorname{Li}(x)+O\!\left(\sqrt{x}\log x\right)`,
        note: "成立时，素数的“波动噪声”被限制在近似平方根尺度。",
      },
      {
        number: "05",
        label: "尚未证明",
        kicker: "大量验证 ≠ 普遍证明",
        title: "再多已检查零点，也无法替代对无限的证明",
        body: "计算已经验证极高范围内的零点位于临界线，但猜想要求对无穷多个零点都成立。它仍是克雷数学研究所的千禧年难题之一。",
        math: String.raw`\forall\rho,\ \zeta(\rho)=0,\ 0<\Re(\rho)<1\Rightarrow\Re(\rho)=\frac12`,
        note: "可视化展示结构与证据，不把尚未解决的问题写成既成定理。",
      },
    ],
  },
  godel: {
    ...concepts[2],
    year: "1931 / META",
    stageLabel: "FORMAL SYSTEM / SELF-REFERENCE",
    stageHint: "拖动旋转 · 增加编码层级",
    stageAria: "哥德尔不完备定理自指结构互动模型",
    observation: "MARGIN NOTE",
    control: {
      label: "自指层级 n",
      min: 1,
      max: 7,
      step: 1,
      initial: 3,
      digits: 0,
    },
    steps: [
      {
        number: "01",
        label: "形式系统",
        kicker: "公理、符号与推演规则",
        title: "先把证明变成可以机械检查的符号链",
        body: "形式系统从有限或可有效描述的公理出发，按明确规则推出定理。哥德尔讨论的是足够表达基本算术、并且能有效枚举公理的系统。",
        math: String.raw`T\vdash\varphi`,
        note: "“形式化”要求每一步都能被规则检查，不依赖直觉跳跃。",
      },
      {
        number: "02",
        label: "算术编码",
        kicker: "让句子谈论句子",
        title: "符号、公式与证明都可以被编码成整数",
        body: "哥德尔编号把语法对象映射为自然数，于是“x 是某个公式的证明”也能在算术内部表达。系统获得了一面能够描述自身语法的镜子。",
        math: String.raw`\ulcorner\varphi\urcorner\in\mathbb N`,
        note: "增加层级，观察一条陈述如何被编码、再作为另一条陈述的对象。",
      },
      {
        number: "03",
        label: "自指句",
        kicker: "这句话在 T 中不可证明",
        title: "对角化制造出关于自身可证性的陈述",
        body: "借助对角引理，可以构造句子 G，使它在系统内等价于“G 不可在 T 中证明”。这不是普通语言悖论，而是严格的算术构造。",
        math: String.raw`T\vdash G\leftrightarrow\neg\operatorname{Prov}_T(\ulcorner G\urcorner)`,
        note: "画面中的缺口表示系统无法从内部把这条回路完全封闭。",
      },
      {
        number: "04",
        label: "第一定理",
        kicker: "一致性带来不完备",
        title: "足够强且一致的系统，总有无法决定的句子",
        body: "在标准条件下，如果 T 一致，就存在句子既不能在 T 中证明，也不能在 T 中否证。这里的“不完备”是特定形式系统的边界，不是说所有数学都不可靠。",
        math: String.raw`T\nvdash G\quad\text{且}\quad T\nvdash\neg G`,
        note: "更换或加强公理可以决定某些旧问题，但新的系统仍会出现自己的不可判定句。",
      },
      {
        number: "05",
        label: "第二定理",
        kicker: "系统无法独自担保自身",
        title: "系统不能在内部证明自己的相容性",
        body: "满足条件且一致的系统 T，不能在自身内部证明 Con(T)。证明相容性通常需要站到更强的元系统中，而那个元系统也会面对同类问题。",
        math: String.raw`T\nvdash\operatorname{Con}(T)`,
        note: "不完备性划出形式证明的结构边界，并不否定数学证明本身。",
      },
    ],
  },
  mandelbrot: {
    ...concepts[3],
    year: "1980 / z² + c",
    stageLabel: "COMPLEX DYNAMICS / ESCAPE FIELD",
    stageHint: "拖动旋转 · 增加迭代深度",
    stageAria: "曼德博集合逃逸时间互动模型",
    observation: "COAST NOTE",
    control: {
      label: "迭代深度 N",
      min: 8,
      max: 96,
      step: 4,
      initial: 48,
      digits: 0,
    },
    steps: [
      {
        number: "01",
        label: "一条规则",
        kicker: "从 z₀ = 0 出发",
        title: "把结果平方，再加上同一个复数 c",
        body: "对复平面中的每个参数 c，从 z₀=0 开始重复迭代。规则极短，但不同 c 会产生完全不同的长期行为。",
        math: String.raw`z_{n+1}=z_n^2+c,\qquad z_0=0`,
        note: "拖动画面时，你看到的是参数平面，不是单条轨道在物理空间中的路径。",
      },
      {
        number: "02",
        label: "是否逃逸",
        kicker: "有界与发散的分界",
        title: "轨道永远有界的 c，组成曼德博集合",
        body: "如果迭代序列始终没有逃向无穷远，则参数 c 属于集合 M。只要某一步满足 |zₙ|>2，之后就必然逃逸。",
        math: String.raw`M=\{c\in\mathbb C:\{z_n\}_{n\ge0}\ \text{有界}\}`,
        note: "深色内陆表示未逃逸区域；海岸亮度表示逃逸速度的层次。",
      },
      {
        number: "03",
        label: "增加迭代",
        kicker: "海岸线逐步显影",
        title: "有限计算只能得到越来越精细的近似",
        body: "把最大迭代次数 N 调高，更多靠近边界的点才显露真实归属。边界附近存在极长的暂态，因此也是细节最密集的区域。",
        math: String.raw`n_{\mathrm{escape}}(c)=\min\{n:|z_n|>2\}`,
        note: "N 越大，轮廓越稳定，但任何有限像素图仍只是连续集合的采样。",
      },
      {
        number: "04",
        label: "无限细节",
        kicker: "自相似，但并非处处复制",
        title: "放大后会遇见相似结构，也会遇见全新的海湾",
        body: "曼德博集合的边界具有分形结构。小型“曼德博宝宝”会反复出现，但其周围纹理受不同周期成分影响，并不是简单复制粘贴。",
        math: String.raw`\partial M\ \text{具有无限层级的局部结构}`,
        note: "“自相似”在这里包含变形与新结构，不等于每一级都完全相同。",
      },
      {
        number: "05",
        label: "参数地图",
        kicker: "一张动力系统的总索引",
        title: "每个点都对应一种二次迭代系统",
        body: "M 不是单一分形图案，而是所有二次多项式 z²+c 的参数地图。主心形、圆瓣和细丝记录了吸引周期与稳定区域的组织方式。",
        math: String.raw`f_c(z)=z^2+c`,
        note: "从一条递推式出发，参数空间长出了完整的动力学地理。",
      },
    ],
  },
  poincare: {
    ...concepts[4],
    year: "1904—2003 / S³",
    stageLabel: "3-MANIFOLD / RICCI FLOW",
    stageHint: "拖动旋转 · 推进流动时间",
    stageAria: "庞加莱猜想与曲率流互动模型",
    observation: "TOPOLOGY NOTE",
    control: {
      label: "流动时间 τ",
      min: 0,
      max: 1,
      step: 0.02,
      initial: 0.12,
      digits: 2,
    },
    steps: [
      {
        number: "01",
        label: "辨认空间",
        kicker: "局部像三维欧氏空间",
        title: "三维流形可以弯曲，却没有局部断裂",
        body: "三维流形在每个足够小的邻域里都像普通三维空间，但整体可能拥有复杂拓扑。问题是：哪些全局条件足以认出三维球面 S³？",
        math: String.raw`M^3\ \text{locally resembles}\ \mathbb R^3`,
        note: "画面表现的是抽象流形的结构，不是嵌入四维空间后的真实外观。",
      },
      {
        number: "02",
        label: "收缩闭环",
        kicker: "单连通",
        title: "每一条闭合环路，都能连续缩成一个点",
        body: "若流形中任何闭合曲线都可以在空间内部连续收缩为一点，它就是单连通的。甜甜圈不满足，因为绕洞的环无法越过洞口。",
        math: String.raw`\pi_1(M)=0`,
        note: "闭环能否收缩，是探测空间中“洞”的核心方法。",
      },
      {
        number: "03",
        label: "猜想",
        kicker: "紧致 × 无边界 × 单连通",
        title: "满足这些条件的三维空间，应当就是三维球面",
        body: "庞加莱猜想断言：每个闭的、单连通三维流形都与三维球面同胚。这里说的是拓扑等价，不要求几何形状或曲率一模一样。",
        math: String.raw`M^3\ \text{closed},\ \pi_1(M)=0\Rightarrow M\cong S^3`,
        note: "可以拉伸和弯曲，但不能撕裂、粘合或穿洞。",
      },
      {
        number: "04",
        label: "曲率流",
        kicker: "让几何像热量一样扩散",
        title: "Ricci 流逐渐抚平曲率，也会暴露奇点",
        body: "Hamilton 提出用 Ricci 流演化度量。高曲率区域会被重新分配，但流动可能形成奇点；理解并处理这些奇点是证明的核心障碍。",
        math: String.raw`\frac{\partial g}{\partial t}=-2\,\operatorname{Ric}(g)`,
        note: "推进 τ，表面逐渐均匀；这只是曲率扩散的概念模型。",
      },
      {
        number: "05",
        label: "佩雷尔曼",
        kicker: "熵、无局部塌缩与手术",
        title: "控制奇点之后，空间的拓扑类型被完整识别",
        body: "佩雷尔曼在 2002—2003 年的预印本中完成关键论证，建立 Ricci 流带手术所需的控制，并证明更广泛的 Thurston 几何化猜想，庞加莱猜想随之成立。",
        math: String.raw`M^3\simeq S^3`,
        note: "这章呈现证明路线的骨架，不把几何分析的技术细节压缩成一次视觉变形。",
      },
    ],
  },
  pnp: {
    ...concepts[5],
    year: "1971 / COMPLEXITY",
    stageLabel: "SEARCH SPACE / CERTIFICATE PATH",
    stageHint: "拖动旋转 · 增加问题规模",
    stageAria: "P 与 NP 搜索空间互动模型",
    observation: "COMPLEXITY NOTE",
    control: {
      label: "问题规模 n",
      min: 4,
      max: 12,
      step: 1,
      initial: 7,
      digits: 0,
    },
    steps: [
      {
        number: "01",
        label: "快速求解",
        kicker: "P：多项式时间",
        title: "有些问题能随输入规模可控地增长",
        body: "P 类包含可以由确定性算法在多项式时间内求解的判定问题。多项式不是“永远很快”，但它把增长控制在理论上可扩展的范围内。",
        math: String.raw`\mathrm P=\bigcup_{k\ge1}\operatorname{TIME}(n^k)`,
        note: "改变规模 n，观察搜索空间增长；模型展示趋势，不代表某个具体算法的实际耗时。",
      },
      {
        number: "02",
        label: "快速验证",
        kicker: "NP：给出证书就能检查",
        title: "出口也许难找，但一条正确路径可以很快验明",
        body: "NP 类问题的“是”实例拥有多项式长度证书，并可在多项式时间内验证。NP 不是“非多项式”，也不等于所有困难问题。",
        math: String.raw`x\in L\iff\exists y,\ |y|\le\operatorname{poly}(|x|),\ V(x,y)=1`,
        note: "玫红路径代表一份候选证书；检查路径比从全部岔路中发现它更直接。",
      },
      {
        number: "03",
        label: "核心问题",
        kicker: "P 是否等于 NP？",
        title: "凡是容易验证的答案，也都容易找到吗",
        body: "我们知道 P⊆NP，但不知道包含是否严格。如果 P=NP，大量搜索、规划与组合优化问题会获得全新的理论算法；若不等，则存在本质上的求解—验证鸿沟。",
        math: String.raw`\mathrm P\stackrel{?}{=}\mathrm{NP}`,
        note: "问题讨论最坏情况与渐近复杂度，不是说每个现实实例都同样难。",
      },
      {
        number: "04",
        label: "完全问题",
        kicker: "所有 NP 问题汇聚的关口",
        title: "解出任意一个 NP 完全问题，就会解出整个 NP",
        body: "SAT 是第一个被证明 NP 完全的问题。任何 NP 问题都能在多项式时间归约到 SAT；因此若 SAT∈P，则 P=NP。",
        math: String.raw`\mathrm{SAT}\in\mathrm P\Rightarrow\mathrm P=\mathrm{NP}`,
        note: "图中的多条支路汇向同一关口，表示归约关系而非问题表面的相似。",
      },
      {
        number: "05",
        label: "仍是开放问题",
        kicker: "证据很多，证明仍缺席",
        title: "几十年的失败，尚未构成 P≠NP 的证明",
        body: "复杂性理论已经发现多种证明障碍，也建立大量条件性结果，但 P 与 NP 的关系依然未知。它同样是千禧年难题之一。",
        math: String.raw`\mathrm P\subseteq\mathrm{NP}\quad\text{已知；等号未知}`,
        note: "系统明确保留“未知”状态，避免把广泛信念误写成定理。",
      },
    ],
  },
};
